name: 'nest-deploy'
on: 
  push

jobs: 
  nest-deploy:
    name: Nest Deploy
    runs-on: ubuntu-latest
    environment: deploy
    steps: 
      - name: Connect via SSH
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd ${{ secrets.DIRECTORY }}            
            git pull
            systemctl -- user daemon reload
            systemctl --user enable $ {{ secrets.SERVICE }}
            systemctl --user start $ {{ secrets.SERVICE}}