name: Nest Deploy
on: 
  push

jobs: 
  nest-deploy:
    name: Nest Deploy
    runs-on: ubuntu-latest
    environment: deploy
    steps: 
      - name: Deployment
        uses: phthallo/nest-deploy@v1.0.2
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          directory: ${{ secrets.DIRECTORY }}
          deployscript: ${{ secrets.SCRIPT }}
